### ISSUE TITLE
Error compiling cjdns OS X 10.8.5 (XCode 5.1.1)

### ISSUE THREAD

**Issue by openberkeley** [cjdelisle/cjdns#734]
3 errors generated.

    at error (/Users/openbsd/Downloads/cjdns-master/node_build/builder.js:52:15)
    at /Users/openbsd/Downloads/cjdns-master/node_build/builder.js:115:22
    at /Users/openbsd/Downloads/cjdns-master/node_build/builder.js:85:13
    at ChildProcess.<anonymous> (/Users/openbsd/Downloads/cjdns-master/node_build/Semaphore.js:7:30)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

**Comment by cjdelisle** [comment]
you pasted the wrong part, the actual error is above that...


On 01/29/2015 09:34 PM, openberkeley wrote:
> 3 errors generated.
> 
>     at error (/Users/openbsd/Downloads/cjdns-master/node_build/builder.js:52:15)
>     at /Users/openbsd/Downloads/cjdns-master/node_build/builder.js:115:22
>     at /Users/openbsd/Downloads/cjdns-master/node_build/builder.js:85:13
>     at ChildProcess.<anonymous> (/Users/openbsd/Downloads/cjdns-master/node_build/Semaphore.js:7:30)
>     at ChildProcess.emit (events.js:98:17)
>     at maybeClose (child_process.js:766:16)
>     at Socket.<anonymous> (child_process.js:979:11)
>     at Socket.emit (events.js:95:17)
>     at Pipe.close (net.js:466:12)
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/cjdelisle/cjdns/issues/734
> 

-- 
Satire is the escape hatch from the cycle of sorrow, hatred and violence. #JeSuisCharlie

**Comment by openberkeley** [comment]
Hi, matey! 

Im pretty sure everything works well) but not for me) cause Im not so skilled to use Git

Anyway.. Im just reinstall my OSX and did another try. Now I have new error:

________________________
cjdns-master/build_darwin/dependencies/cnacl/node_build/RandomBytes.js:9
________________________

Machine specs: MacBookPro6,2 OSX 10.8.5 XCode 5.1.1 CLT 5B1008 Python 2.7 GCC Apple LLVM version 5.1 (clang-503.0.40) tryed nodejs both from macport and them node.pkg - still no luck.

Ultra_respect for your talents! I believe in you and mesh network. May be some nub-friendly advice from you?)

**Comment by cjdelisle** [comment]
paste like a shitton of the backscroll, one of the lines is significant but without seeing *all* of it I don't know which.

On 01/29/2015 11:59 PM, openberkeley wrote:
> Hi, matey! 
> 
> Im pretty sure everything works well) but not for me) cause Im not so skilled to use Git
> 
> Anyway.. Im just reinstall my OSX and did another try. Now I have new error:
> 
> ________________________
> cjdns-master/build_darwin/dependencies/cnacl/node_build/RandomBytes.js:9
> ________________________
> 
> Machine specs: MacBookPro6,2 OSX 10.8.5 XCode 5.1.1 CLT 5B1008 Python 2.7 GCC Apple LLVM version 5.1 (clang-503.0.40) tryed nodejs both from macport and them node.pkg - still no luck.
> 
> Ultra_respect for your talents! I believe in you and mesh network. May be some nub-friendly advice from you?)
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/cjdelisle/cjdns/issues/734#issuecomment-72121968
> 

-- 
Satire is the escape hatch from the cycle of sorrow, hatred and violence. #JeSuisCharlie

**Comment by openberkeley** [comment]
Edouards-MacBook-Pro:/ openberkeley$ cd ~/Downloads/cjdns-master
Edouards-MacBook-Pro:cjdns-master openberkeley$ ./do
Initialize 2ms
Build NaCl
Creating directories
Total build time: 0ms.

/Users/openberkeley/Downloads/cjdns-master/build_darwin/dependencies/cnacl/node_build/RandomBytes.js:9
      if (err) { throw err; }
                       ^
Error: EACCES, open 'jsbuild/include_internal/randombytes.h'
Edouards-MacBook-Pro:cjdns-master openberkeley$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin12.6.0
Thread model: posix
Edouards-MacBook-Pro:cjdns-master openberkeley$

**Comment by openberkeley** [comment]
Hello!

This method solves my issue:

https://github.com/cjdelisle/cjdns/commit/420e7ebe75ffa51c16e5930a55a3bcecadfd111d

Finally I get cjdns-stable-0.7 working.
Issue closed.

Cheers!
