### ISSUE TITLE
Missing include in darwin segment of code

### ISSUE THREAD

**Issue by Andrepuel** [cjdelisle/cjdns#735]
In 97161a5fef6b98ffbba94888587bd9ce733c2278 I needed to do the following modification to make cjdns compilable on OSX:

    diff --git a/util/platform/netdev/NetPlatform_darwin.c b/util/platform/netdev/NetPlatform_darwin.c
    index e626a79..dede10c 100644
    --- a/util/platform/netdev/NetPlatform_darwin.c
    +++ b/util/platform/netdev/NetPlatform_darwin.c
    @@ -15,6 +15,7 @@
     #include "exception/Except.h"
     #include "util/platform/netdev/NetPlatform.h"
     #include "util/AddrTools.h"
    +#include "util/platform/Sockaddr.h"
     
     #include <errno.h>
     #include <stdio.h>

**Comment by geekspourjesus** [comment]
I had the same problem, and the patch is working for me on MacOsX 10.9.5

**Comment by wKovacs64** [comment]
This works on 10.10.2 as well. Going to open a pull request, @Andrepuel ?

**Comment by Andrepuel** [comment]
Yes, https://github.com/cjdelisle/cjdns/pull/742
I just wanted to do a bisect first to figure out what caused this bug, just to make sure my solution wasnt breaking something else.
